// Code generated by Slice Machine. DO NOT EDIT.

import Members from './Members/index.svelte';
import TitleContainer from './TitleContainer/index.svelte';

export const components = {
	members: Members,
	rich_text: TitleContainer
};
