// Code generated by Slice Machine. DO NOT EDIT.

import Members from './Members/index.svelte';
import Squad from './Squad/index.svelte';

export const components = {
	members: Members,
	squad: Squad
};
