// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = FooterContainerSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
	/**
	 * Slice Zone field in *footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

type HeaderDocumentDataSlicesSlice = HeaderContainerSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
	/**
	 * Slice Zone field in *header*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

type MemberDocumentDataSlicesSlice = MemberAboutContainerSlice;

/**
 * Content for member documents
 */
interface MemberDocumentData {
	/**
	 * image field in *member*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *member*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Slice Zone field in *member*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<MemberDocumentDataSlicesSlice>;
}

/**
 * member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<MemberDocumentData>,
	'member',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| SearchContainerSlice
	| FooterContainerSlice
	| HeaderContainerSlice
	| RichTextSlice
	| MembersSlice
	| AboutContainerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

type SearchDocumentDataSlicesSlice = SearchContainerSlice;

/**
 * Content for search documents
 */
interface SearchDocumentData {
	/**
	 * Slice Zone field in *search*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SearchDocumentDataSlicesSlice>;
}

/**
 * search document from Prismic
 *
 * - **API ID**: `search`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SearchDocumentData>,
	'search',
	Lang
>;

export type AllDocumentTypes =
	| FooterDocument
	| HeaderDocument
	| MemberDocument
	| PageDocument
	| SearchDocument;

/**
 * Primary content in *AboutContainer → Primary*
 */
export interface AboutContainerSliceDefaultPrimary {
	/**
	 * about_title field in *AboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_container.primary.about_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_title: prismic.KeyTextField;

	/**
	 * about_text field in *AboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_container.primary.about_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	about_text: prismic.KeyTextField;

	/**
	 * about_image field in *AboutContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_container.primary.about_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	about_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *AboutContainer*
 */
type AboutContainerSliceVariation = AboutContainerSliceDefault;

/**
 * AboutContainer Shared Slice
 *
 * - **API ID**: `about_container`
 * - **Description**: AboutContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutContainerSlice = prismic.SharedSlice<
	'about_container',
	AboutContainerSliceVariation
>;

/**
 * Primary content in *FooterContainer → Primary*
 */
export interface FooterContainerSliceDefaultPrimary {
	/**
	 * footer_title field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	footer_title: prismic.KeyTextField;

	/**
	 * footer_image field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	footer_image: prismic.ImageField<never>;

	/**
	 * footer_link_title field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_link_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	footer_link_title: prismic.KeyTextField;

	/**
	 * footer_link field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	footer_link: prismic.LinkField;
}

/**
 * Default variation for FooterContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FooterContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FooterContainer*
 */
type FooterContainerSliceVariation = FooterContainerSliceDefault;

/**
 * FooterContainer Shared Slice
 *
 * - **API ID**: `footer_container`
 * - **Description**: FooterContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContainerSlice = prismic.SharedSlice<
	'footer_container',
	FooterContainerSliceVariation
>;

/**
 * Primary content in *HeaderContainer → Primary*
 */
export interface HeaderContainerSliceDefaultPrimary {
	/**
	 * Logo_title field in *HeaderContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header_container.primary.logo_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	logo_title: prismic.KeyTextField;

	/**
	 * logo_image field in *HeaderContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header_container.primary.logo_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeaderContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeaderContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeaderContainer*
 */
type HeaderContainerSliceVariation = HeaderContainerSliceDefault;

/**
 * HeaderContainer Shared Slice
 *
 * - **API ID**: `header_container`
 * - **Description**: HeaderContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderContainerSlice = prismic.SharedSlice<
	'header_container',
	HeaderContainerSliceVariation
>;

/**
 * Primary content in *MemberAboutContainer → Primary*
 */
export interface MemberAboutContainerSliceDefaultPrimary {
	/**
	 * heading_1 field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.heading_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading_1: prismic.KeyTextField;

	/**
	 * highlight_1 field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.highlight_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	highlight_1: prismic.KeyTextField;

	/**
	 * highlight_2 field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.highlight_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	highlight_2: prismic.KeyTextField;

	/**
	 * highlight_3 field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.highlight_3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	highlight_3: prismic.KeyTextField;

	/**
	 * heading_2 field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.heading_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	heading_2: prismic.KeyTextField;

	/**
	 * paragraph_more_about field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.paragraph_more_about
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	paragraph_more_about: prismic.KeyTextField;

	/**
	 * image_more_about field in *MemberAboutContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_about_container.primary.image_more_about
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image_more_about: prismic.ImageField<never>;
}

/**
 * Default variation for MemberAboutContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberAboutContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MemberAboutContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *MemberAboutContainer*
 */
type MemberAboutContainerSliceVariation = MemberAboutContainerSliceDefault;

/**
 * MemberAboutContainer Shared Slice
 *
 * - **API ID**: `member_about_container`
 * - **Description**: MemberAboutContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberAboutContainerSlice = prismic.SharedSlice<
	'member_about_container',
	MemberAboutContainerSliceVariation
>;

/**
 * Primary content in *Members → Items*
 */
export interface MembersSliceDefaultItem {
	/**
	 * members field in *Members → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: members.items[].members
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	members: prismic.ContentRelationshipField<'member'>;
}

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<MembersSliceDefaultItem>
>;

/**
 * Slice variation for *Members*
 */
type MembersSliceVariation = MembersSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `members`
 * - **Description**: Members
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSlice = prismic.SharedSlice<'members', MembersSliceVariation>;

/**
 * Primary content in *CallToActionContainer → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * call_to_action_heading field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.call_to_action_heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	call_to_action_heading: prismic.KeyTextField;

	/**
	 * call_to_action_image field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.call_to_action_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	call_to_action_image: prismic.ImageField<never>;

	/**
	 * search_button field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.search_button
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	search_button: prismic.KeyTextField;
}

/**
 * Default variation for CallToActionContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CallToActionContainer*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * CallToActionContainer Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *SearchContainer → Primary*
 */
export interface SearchContainerSliceDefaultPrimary {
	/**
	 * search_title field in *SearchContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search_container.primary.search_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	search_title: prismic.KeyTextField;

	/**
	 * input_placeholder field in *SearchContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search_container.primary.input_placeholder
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	input_placeholder: prismic.KeyTextField;

	/**
	 * input_svg field in *SearchContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: search_container.primary.input_svg
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	input_svg: prismic.ImageField<never>;
}

/**
 * Default variation for SearchContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SearchContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SearchContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SearchContainer*
 */
type SearchContainerSliceVariation = SearchContainerSliceDefault;

/**
 * SearchContainer Shared Slice
 *
 * - **API ID**: `search_container`
 * - **Description**: SearchContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SearchContainerSlice = prismic.SharedSlice<
	'search_container',
	SearchContainerSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataSlicesSlice,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataSlicesSlice,
			MemberDocument,
			MemberDocumentData,
			MemberDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SearchDocument,
			SearchDocumentData,
			SearchDocumentDataSlicesSlice,
			AllDocumentTypes,
			AboutContainerSlice,
			AboutContainerSliceDefaultPrimary,
			AboutContainerSliceVariation,
			AboutContainerSliceDefault,
			FooterContainerSlice,
			FooterContainerSliceDefaultPrimary,
			FooterContainerSliceVariation,
			FooterContainerSliceDefault,
			HeaderContainerSlice,
			HeaderContainerSliceDefaultPrimary,
			HeaderContainerSliceVariation,
			HeaderContainerSliceDefault,
			MemberAboutContainerSlice,
			MemberAboutContainerSliceDefaultPrimary,
			MemberAboutContainerSliceVariation,
			MemberAboutContainerSliceDefault,
			MembersSlice,
			MembersSliceDefaultItem,
			MembersSliceVariation,
			MembersSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			SearchContainerSlice,
			SearchContainerSliceDefaultPrimary,
			SearchContainerSliceVariation,
			SearchContainerSliceDefault
		};
	}
}
