// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = FooterSlice | HeaderSlice | MainSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for squadMembers documents
 */
interface SquadmembersDocumentData {
  /**
   * memberName field in *squadMembers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.membername
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  membername: prismic.KeyTextField;

  /**
   * memberImg field in *squadMembers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.memberimg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  memberimg: prismic.ImageField<never>;

  /**
   * githubLink field in *squadMembers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: squadmembers.githublink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  githublink: prismic.LinkField;
}

/**
 * squadMembers document from Prismic
 *
 * - **API ID**: `squadmembers`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadmembersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadmembersDocumentData>,
    "squadmembers",
    Lang
  >;

type SquadsDocumentDataSlicesSlice =
  | FooterSlice
  | HeaderSlice
  | SquadMembersSlice;

/**
 * Content for Squad documents
 */
interface SquadsDocumentData {
  /**
   * squadName field in *Squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squads.squadname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  squadname: prismic.KeyTextField;

  /**
   * Slice Zone field in *Squad*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squads.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadsDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: squads.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Squad*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squads.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Squad*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: squads.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Squad document from Prismic
 *
 * - **API ID**: `squads`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SquadsDocumentData>, "squads", Lang>;

type SquadselectDocumentDataSlicesSlice =
  | HeaderSlice
  | FooterSlice
  | SquadSelectionSlice;

/**
 * Content for squadSelect documents
 */
interface SquadselectDocumentData {
  /**
   * Slice Zone field in *squadSelect*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squadselect.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadselectDocumentDataSlicesSlice>
  /**
   * Meta Description field in *squadSelect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: squadselect.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *squadSelect*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squadselect.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *squadSelect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: squadselect.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * squadSelect document from Prismic
 *
 * - **API ID**: `squadselect`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadselectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadselectDocumentData>,
    "squadselect",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | SquadmembersDocument
  | SquadsDocument
  | SquadselectDocument;

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Default variation for Main Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Main*
 */
type MainSliceVariation = MainSliceDefault;

/**
 * Main Shared Slice
 *
 * - **API ID**: `main`
 * - **Description**: Main
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainSlice = prismic.SharedSlice<"main", MainSliceVariation>;

/**
 * Primary content in *SquadMembers → Items*
 */
export interface SquadMembersSliceDefaultItem {
  /**
   * memberName field in *SquadMembers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_members.items[].membername
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  membername: prismic.KeyTextField;

  /**
   * memberProfile field in *SquadMembers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_members.items[].memberProfile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  memberProfile: prismic.ImageField<never>;

  /**
   * githubLink field in *SquadMembers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_members.items[].githublink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  githublink: prismic.LinkField;
}

/**
 * Default variation for SquadMembers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadMembersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SquadMembersSliceDefaultItem>
>;

/**
 * Slice variation for *SquadMembers*
 */
type SquadMembersSliceVariation = SquadMembersSliceDefault;

/**
 * SquadMembers Shared Slice
 *
 * - **API ID**: `squad_members`
 * - **Description**: SquadMembers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadMembersSlice = prismic.SharedSlice<
  "squad_members",
  SquadMembersSliceVariation
>;

/**
 * Primary content in *SquadSelection → Primary*
 */
export interface SquadSelectionSliceDefaultPrimary {
  /**
   * title field in *SquadSelection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_selection.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *SquadSelection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_selection.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * squadA field in *SquadSelection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_selection.primary.squada
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  squada: prismic.LinkField;

  /**
   * squadB field in *SquadSelection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_selection.primary.squadb
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  squadb: prismic.LinkField;

  /**
   * contentImg field in *SquadSelection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_selection.primary.contentimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contentimg: prismic.ImageField<never>;
}

/**
 * Default variation for SquadSelection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSelectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SquadSelectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SquadSelection*
 */
type SquadSelectionSliceVariation = SquadSelectionSliceDefault;

/**
 * SquadSelection Shared Slice
 *
 * - **API ID**: `squad_selection`
 * - **Description**: SquadSelection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSelectionSlice = prismic.SharedSlice<
  "squad_selection",
  SquadSelectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SquadmembersDocument,
      SquadmembersDocumentData,
      SquadsDocument,
      SquadsDocumentData,
      SquadsDocumentDataSlicesSlice,
      SquadselectDocument,
      SquadselectDocumentData,
      SquadselectDocumentDataSlicesSlice,
      AllDocumentTypes,
      FooterSlice,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceVariation,
      HeaderSliceDefault,
      MainSlice,
      MainSliceVariation,
      MainSliceDefault,
      SquadMembersSlice,
      SquadMembersSliceDefaultItem,
      SquadMembersSliceVariation,
      SquadMembersSliceDefault,
      SquadSelectionSlice,
      SquadSelectionSliceDefaultPrimary,
      SquadSelectionSliceVariation,
      SquadSelectionSliceDefault,
    };
  }
}
