// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type FooterDocumentDataSlicesSlice = FooterContainerSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
	/**
	 * Slice Zone field in *footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

type HeaderDocumentDataSlicesSlice = HeaderContainerSlice;

/**
 * Content for header documents
 */
interface HeaderDocumentData {
	/**
	 * Slice Zone field in *header*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

/**
 * Content for member documents
 */
interface MemberDocumentData {
	/**
	 * image field in *member*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *member*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
}

/**
 * member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<MemberDocumentData>,
	'member',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| FooterContainerSlice
	| HeaderContainerSlice
	| RichTextSlice
	| MembersSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | MemberDocument | PageDocument;

/**
 * Primary content in *FooterContainer → Primary*
 */
export interface FooterContainerSliceDefaultPrimary {
	/**
	 * footer_title field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	footer_title: prismic.KeyTextField;

	/**
	 * footer_image field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	footer_image: prismic.ImageField<never>;

	/**
	 * footer_link field in *FooterContainer → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_container.primary.footer_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	footer_link: prismic.LinkField;
}

/**
 * Default variation for FooterContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FooterContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FooterContainer*
 */
type FooterContainerSliceVariation = FooterContainerSliceDefault;

/**
 * FooterContainer Shared Slice
 *
 * - **API ID**: `footer_container`
 * - **Description**: FooterContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContainerSlice = prismic.SharedSlice<
	'footer_container',
	FooterContainerSliceVariation
>;

/**
 * Primary content in *HeaderContainer → Primary*
 */
export interface HeaderContainerSliceDefaultPrimary {
	/**
	 * Logo_title field in *HeaderContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header_container.primary.logo_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	logo_title: prismic.KeyTextField;

	/**
	 * logo_image field in *HeaderContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header_container.primary.logo_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeaderContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderContainerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeaderContainerSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeaderContainer*
 */
type HeaderContainerSliceVariation = HeaderContainerSliceDefault;

/**
 * HeaderContainer Shared Slice
 *
 * - **API ID**: `header_container`
 * - **Description**: HeaderContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderContainerSlice = prismic.SharedSlice<
	'header_container',
	HeaderContainerSliceVariation
>;

/**
 * Primary content in *Members → Items*
 */
export interface MembersSliceDefaultItem {
	/**
	 * members field in *Members → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: members.items[].members
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	members: prismic.ContentRelationshipField<'member'>;
}

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<MembersSliceDefaultItem>
>;

/**
 * Slice variation for *Members*
 */
type MembersSliceVariation = MembersSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `members`
 * - **Description**: Members
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSlice = prismic.SharedSlice<'members', MembersSliceVariation>;

/**
 * Primary content in *CallToActionContainer → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * call_to_action_heading field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.call_to_action_heading
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	call_to_action_heading: prismic.KeyTextField;

	/**
	 * call_to_action_image field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.call_to_action_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	call_to_action_image: prismic.ImageField<never>;

	/**
	 * search_button field in *CallToActionContainer → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.search_button
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	search_button: prismic.KeyTextField;
}

/**
 * Default variation for CallToActionContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *CallToActionContainer*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * CallToActionContainer Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataSlicesSlice,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataSlicesSlice,
			MemberDocument,
			MemberDocumentData,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			FooterContainerSlice,
			FooterContainerSliceDefaultPrimary,
			FooterContainerSliceVariation,
			FooterContainerSliceDefault,
			HeaderContainerSlice,
			HeaderContainerSliceDefaultPrimary,
			HeaderContainerSliceVariation,
			HeaderContainerSliceDefault,
			MembersSlice,
			MembersSliceDefaultItem,
			MembersSliceVariation,
			MembersSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault
		};
	}
}
